server:
  port: 8081

spring:
  sql:
    init-mode: always

  datasource:
    url: jdbc:h2:mem:example-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        default_schema: public

  security.jwt.token.secret-key: HelpDesk
  security.jwt.token.expire-length: 36000000

  permitted.url: http://localhost:3000/

  mail.host: smtp.gmail.com
  mail.port: 587
  mail.username: tt0188723@gmail.com
  mail.password: T_T0188723

